### ISSUE TITLE
New pagedown version

### ISSUE THREAD

**Issue by tvroylandt** [rfortherestofus/pagedreport#22]
A big point : the new `pagedown` version, in development now, breaks some style.
So I specified the version to use in the Description (0.13, the one on CRAN now). 

But we need to keep in mind that we will need to update it in the next couple of months.

**Comment by RLesur** [comment]
Sorry for that 🙏 
@yihui, have you already planned the next release of pagedown?

**Comment by yihui** [comment]
@RLesur Normally I make a release every month, but since @tvroylandt has discovered a problem, I'll definitely wait until the problem is resolved.

**Comment by tvroylandt** [comment]
Main problem is that I use some `position: absolute` for title page. And it seems that with the devlopment version, position is broken. I will investigate. Thank you

**Comment by cderv** [comment]
Glad you opened this so that we are aware ! 😄 

I think it would be an interesting idea to have your CI run tests on dev **pkgdown** also if not already. That way, you would be notify as soon as something breaks here and you can report quick. You could have two workflows, one using CRAN version and another using always the last dev version ? 

This would allow to find this issue quicker maybe (it also depends on your test 😅 ). I don't think we mind waiting to delay our scheduled CRAN release by a few days if there is an issue still unsolved on your side. 

When your package will be on CRAN, it believe it will be easier using rev dep checks.

**Comment by tvroylandt** [comment]
Really good idea Christophe ! I will change the CI.

We don't plan to release our package to CRAN now. The idea is still to young.

**Comment by cderv** [comment]
Visual testing is not easy unfortunately, and a lot can vary.

So, you will have to test manually with example you know have specific features.
