### ISSUE TITLE
wrong indent for the numbered list in with hazelnuts template

### ISSUE THREAD

**Issue by FilexD** [rfortherestofus/pagedreport#37]
To my experience : a numbered list is indent wrongly with the hazelnuts template (nearly in the left margin instead of an indent on the right like the bullets list.

**Comment by tvroylandt** [comment]
Thank you for the issue. Could you provide a screenshot and a code example please ?

**Comment by FilexD** [comment]
Here's the code I added to the template:
Before:
This is a good place to demonstrate special features that your template provides. Ideally it should knit out-of-the-box, or at least contain clear instructions as to what needs changing.
![Screenshot_2021-04-28](https://user-images.githubusercontent.com/75352640/116362069-f4c64400-a801-11eb-99e3-11da6592a5ed.png)
![Screenshot_2021-04-28](https://user-images.githubusercontent.com/75352640/116362119-014a9c80-a802-11eb-9488-36674476cb35.png)



The "code" added:
## The numbered list {-}

Here is the test.

1. One
2. Two
3. Three

After : 

## Second level {-}

**Comment by tvroylandt** [comment]
This : https://github.com/rfortherestofus/pagedreport/commit/f842b8728963eda8da733964b8bca6cf0bc130b5 should solve the problem.

The reason is that numbered list have `ol` class instead of `ul` and I just forgot to assign the same properties for both.

Thanks for the issue. Please close if it's ok for you.
